name: Long Running SDK CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  api_key: ${{ secrets.LRS_SERVER_KEY }}
  image_tag: nodejs
  sdk_repo: private-node-js-server-sdk

jobs:
  CD:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LRS repo
        uses: actions/checkout@v4
        with:
          repository: statsig-io/long-running-sdk
          ref: main
          token: ${{ secrets.ROIM }}
      - name: Checkout SDK repo
        uses: actions/checkout@v4
        with:
          repository: statsig-io/${{  env.sdk_repo  }}
          ref: main
          token: ${{ secrets.ROIM }}
          path: ./nodejs/${{  env.sdk_repo  }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: statsig
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: nodejs/Dockerfile
          push: true
          tags: statsig/long-running-sdk:${{ env.image_tag }}
          github-token: ${{ secrets.GH_CI_CD_PAT }}
          build-args: secret_key=${{env.api_key}}
          platforms: linux/amd64
